export enum AllToServerEvents {}

export enum ServerToAllEvents {
    SESSION_UPDATE="SESSION_UPDATE",
    VOTING_PROCESSING_COMPLETED="VOTING_PROCESSING_COMPLETED",
    VOTING_PROCESSING_ERROR="VOTING_PROCESSING_ERROR"
}
