export enum AllToServerEvents {}

export enum ServerToAllEvents {
    SESSION_UPDATE="SESSION_UPDATE",
    TEAM_LEADER_SELECTED="TEAM_LEADER_SELECTED",
    VOTING_COUNTDOWN_UPDATE="VOTING_COUNTDOWN_UPDATE",
    VOTING_PROCESSING_STARTED="VOTING_PROCESSING_STARTED",
    VOTING_PROCESSING_COMPLETED="VOTING_PROCESSING_COMPLETED",
    VOTING_PROCESSING_ERROR="VOTING_PROCESSING_ERROR"
}
